name: secretsforfatloss
favicon: null
layout_spectrum: 0.1428963402286172
typography_spectrum: 0.41405396768823266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3110716831870377
  lightness: 0.6280170555692166
  saturation: 0.03342611389234662
  rhythmicContrast: 0.6767575591802597
purpose: []
